/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateIntervalArgs } from "./CreateIntervalArgs";
import { UpdateIntervalArgs } from "./UpdateIntervalArgs";
import { DeleteIntervalArgs } from "./DeleteIntervalArgs";
import { IntervalCountArgs } from "./IntervalCountArgs";
import { IntervalFindManyArgs } from "./IntervalFindManyArgs";
import { IntervalFindUniqueArgs } from "./IntervalFindUniqueArgs";
import { Interval } from "./Interval";
import { IntervalService } from "../interval.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Interval)
export class IntervalResolverBase {
  constructor(
    protected readonly service: IntervalService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Interval",
    action: "read",
    possession: "any",
  })
  async _intervalsMeta(
    @graphql.Args() args: IntervalCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Interval])
  @nestAccessControl.UseRoles({
    resource: "Interval",
    action: "read",
    possession: "any",
  })
  async intervals(
    @graphql.Args() args: IntervalFindManyArgs
  ): Promise<Interval[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Interval, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Interval",
    action: "read",
    possession: "own",
  })
  async interval(
    @graphql.Args() args: IntervalFindUniqueArgs
  ): Promise<Interval | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Interval)
  @nestAccessControl.UseRoles({
    resource: "Interval",
    action: "create",
    possession: "any",
  })
  async createInterval(
    @graphql.Args() args: CreateIntervalArgs
  ): Promise<Interval> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Interval)
  @nestAccessControl.UseRoles({
    resource: "Interval",
    action: "update",
    possession: "any",
  })
  async updateInterval(
    @graphql.Args() args: UpdateIntervalArgs
  ): Promise<Interval | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Interval)
  @nestAccessControl.UseRoles({
    resource: "Interval",
    action: "delete",
    possession: "any",
  })
  async deleteInterval(
    @graphql.Args() args: DeleteIntervalArgs
  ): Promise<Interval | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
